# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:

    -   id: check-ast
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: check-executables-have-shebangs
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: detect-private-key
    -   id: check-added-large-files
    -   id: check-merge-conflict


-   repo: local
    hooks:

    -   id: ruff
        name: ruff
        entry: ruff
        language: system
        types: [python]
        args:
            - --verbose
            - --per-file-ignores=__init__.py:F401
            - --fix
            - --exit-non-zero-on-fix

    -   id: pyright
        name: pyright
        entry: pyright
        language: system
        types: [python]

    -   id: isort
        name: isort
        entry: isort
        args: [--profile black]
        language: system
        types: [python]

    -   id: black
        name: black
        entry: black
        language: system
        types: [python]

